In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\dell\Downloads\Dataset_Automobile.csv")

In [5]:
df.head(5)

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [9]:
df.shape

(205, 26)

In [11]:
categorical_cols = df.select_dtypes(include=['object']).columns
print(categorical_cols)

Index(['make', 'fuel_type', 'aspiration', 'num_doors', 'body_style',
       'drive_wheels', 'engine_location', 'engine_type', 'num_cylinders',
       'fuel_system'],
      dtype='object')

In [13]:
continuous_cols = [
'normalized_losses','wheel_base','length','width','height',
'curb_weight','engine_size','bore','stroke','compression_ratio',
'horsepower','peak_rpm','city_mpg','highway_mpg','price'
]

In [ ]:
# symboling
# num_doors
# num_of_cylinders

In [15]:
df.isnull().sum()

symboling             0
normalized_losses    41
make                  0
fuel_type             0
aspiration            0
num_doors             2
body_style            0
drive_wheels          0
engine_location       0
wheel_base            0
length                0
width                 0
height                0
curb_weight           0
engine_type           0
num_cylinders         0
engine_size           0
fuel_system           0
bore                  4
stroke                4
compression_ratio     0
horsepower            2
peak_rpm              2
city_mpg              0
highway_mpg           0
price                 4
dtype: int64

In [23]:
# fill missing values in numeric columns
df.fillna(df.mean(numeric_only=True), inplace=True)

# fill missing values in categorical columns
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [25]:
df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [27]:
df.isnull().sum()

symboling            0
normalized_losses    0
make                 0
fuel_type            0
aspiration           0
num_doors            0
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_cylinders        0
engine_size          0
fuel_system          0
bore                 0
stroke               0
compression_ratio    0
horsepower           0
peak_rpm             0
city_mpg             0
highway_mpg          0
price                0
dtype: int64

In [29]:
df_encoded = pd.get_dummies(df, columns=categorical_cols)

In [31]:

print(df_encoded.head())

   symboling  normalized_losses  wheel_base  length  width  height  \
0          3              122.0        88.6   168.8   64.1    48.8
1          3              122.0        88.6   168.8   64.1    48.8
2          1              122.0        94.5   171.2   65.5    52.4
3          2              164.0        99.8   176.6   66.2    54.3
4          2              164.0        99.4   176.6   66.4    54.3

   curb_weight  engine_size  bore  stroke  ...  num_cylinders_twelve  \
0         2548          130  3.47    2.68  ...                 False
1         2548          130  3.47    2.68  ...                 False
2         2823          152  2.68    3.47  ...                 False
3         2337          109  3.19    3.40  ...                 False
4         2824          136  3.19    3.40  ...                 False

   num_cylinders_two  fuel_system_1bbl  fuel_system_2bbl  fuel_system_4bbl  \
0              False             False             False             False
1              False             False             False             False
2              False             False             False             False
3              False             False             False             False
4              False             False             False             False

   fuel_system_idi  fuel_system_mfi  fuel_system_mpfi  fuel_system_spdi  \
0            False            False              True             False
1            False            False              True             False
2            False            False              True             False
3            False            False              True             False
4            False            False              True             False

   fuel_system_spfi
0             False
1             False
2             False
3             False
4             False

[5 rows x 76 columns]

In [33]:
df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0