In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\dell\Downloads\Dataset_Fish_Market.csv")

In [3]:
df.head(5)

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [5]:
df.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

# Label Encoding (for classification tasks)
le = LabelEncoder()
df['Species_encoded'] = le.fit_transform(df['Species'])

# One-Hot Encoding (for regression tasks)
df_onehot = pd.get_dummies(df, columns=['Species'])

In [15]:
df.head()

  Species  Weight  Length1  Length2  Length3   Height   Width  Species_encoded
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200                0
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056                0
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961                0
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555                0
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340                0